schema_version: 1
job_id: 9c7d30eb2f85
best_rank: 1
best_candidate:
  candidate_id: 415
  x_steps: 4
  learning_rate: '0.01'
  weight_decay: '0.01'
  dropout: '0.5'
  tao2: '0.9'
fixed_params:
  dataset: Books-Children
  feature: raw
  sim_reference_eps: null
  feature_dim: null
  scale: null
  random_normal_mean: null
  random_normal_std: null
  shared_value: null
  degree_bucket_num_buckets: null
  degree_bucket_range_max: null
  deepwalk_walk_length: null
  deepwalk_number_walks: null
  deepwalk_window_size: null
  deepwalk_workers: null
  deepwalk_undirected: null
  mechanism: mbm
  x_eps: '0.001'
  m: best
  norm: false
  norm_scale: none
  smoother: hoa
  backbone: sage
  use_nfr: true
defaults:
  dataset:
    data_range:
    - 0.0
    - 1.0
    val_ratio: 0.25
    test_ratio: 0.25
  model:
    hidden_dim: 16
  trainer:
    optimizer: adam
    collect_grad_stats: false
    gradient_clip: false
    gradient_clip_max_norm: 1.0
    sim_epoch_refresh: false
    show_progress: false
    log_every_epoch: false
  stage:
    grid:
      patience: 80
      repeats: 1
      max_epochs: 300
    verify:
      patience: 150
      repeats: 5
      max_epochs: 500
verify_metrics:
  val_acc:
    mean: 40.88454055786133
    std: 0.9152166496431987
    min: 39.601436614990234
    max: 42.187416076660156
    n: 5
  test_acc:
    mean: 40.85228042602539
    std: 0.732861663156917
    min: 40.02809524536133
    max: 41.77116394042969
    n: 5
artifacts:
  verify_summary_csv: /home/hzw/Rethinking_GNN_DP/paper_experiments/figure3/figure3_pipeline3.yaml/dataset=Books-Children/feature=raw/mechanism=mbm/x_eps=0.001/m=best/norm=false/smoother=hoa/backbone=sage/use_nfr=true/verify_top5_summary.csv
  recommended_command_txt: /home/hzw/Rethinking_GNN_DP/paper_experiments/figure3/figure3_pipeline3.yaml/dataset=Books-Children/feature=raw/mechanism=mbm/x_eps=0.001/m=best/norm=false/smoother=hoa/backbone=sage/use_nfr=true/recommended_command.txt
recommended_command: /home/hzw/miniconda3/envs/HZWDP/bin/python main.py --dataset
  Books-Children --feature raw --mechanism mbm --x_eps 0.001 --m best --model sage
  --hidden_dim 16 --smoother hoa --optimizer adam --device cuda --val_ratio 0.25 --test_ratio
  0.25 --data_range 0.0 1.0 --norm false --collect_grad_stats false --gradient_clip
  false --gradient_clip_max_norm 1.0 --sim_epoch_refresh false --show_progress false
  --log_every_epoch false --use_nfr --x_steps 4 --learning_rate 0.01 --weight_decay
  0.01 --dropout 0.5 --max_epochs 500 --patience 150 -s 12345 -r 5 -o /home/hzw/Rethinking_GNN_DP/paper_experiments/figure3/figure3_pipeline3.yaml/dataset=Books-Children/feature=raw/mechanism=mbm/x_eps=0.001/m=best/norm=false/smoother=hoa/backbone=sage/use_nfr=true/final
  --tao2 0.9
