schema_version: 1
job_id: 782765793c8f
best_rank: 1
best_candidate:
  candidate_id: 39
  x_steps: 4
  learning_rate: '0.01'
  weight_decay: '0'
  dropout: '0.75'
  tao2: none
fixed_params:
  dataset: Books-History
  feature: eigen_norm
  sim_reference_eps: null
  feature_dim: 3200
  scale: '1'
  random_normal_mean: null
  random_normal_std: null
  shared_value: null
  degree_bucket_num_buckets: null
  degree_bucket_range_max: null
  deepwalk_walk_length: null
  deepwalk_number_walks: null
  deepwalk_window_size: null
  deepwalk_workers: null
  deepwalk_undirected: null
  mechanism: mbm
  x_eps: inf
  m: best
  norm: false
  norm_scale: none
  smoother: kprop
  backbone: sage
  use_nfr: false
defaults:
  dataset:
    data_range:
    - 0.0
    - 1.0
    val_ratio: 0.25
    test_ratio: 0.25
  model:
    hidden_dim: 16
  trainer:
    optimizer: adam
    collect_grad_stats: false
    gradient_clip: false
    gradient_clip_max_norm: 1.0
    sim_epoch_refresh: false
    show_progress: false
    log_every_epoch: false
  stage:
    grid:
      patience: 80
      repeats: 1
      max_epochs: 300
    verify:
      patience: 150
      repeats: 5
      max_epochs: 500
verify_metrics:
  val_acc:
    mean: 76.22256622314453
    std: 0.5211204792810348
    min: 75.30805206298828
    max: 76.60762786865234
    n: 5
  test_acc:
    mean: 76.57681732177734
    std: 0.40519248245049294
    min: 76.1840591430664
    max: 77.25259399414062
    n: 5
artifacts:
  verify_summary_csv: /home/hzw/Rethinking_GNN_DP/paper_experiments/figure1/search_phase_2/family3/kprop/eigen_norm/dataset=Books-History/feature=eigen_norm/feature_dim=3200/mechanism=mbm/x_eps=inf/m=best/norm=false/smoother=kprop/backbone=sage/use_nfr=false/verify_top5_summary.csv
  recommended_command_txt: /home/hzw/Rethinking_GNN_DP/paper_experiments/figure1/search_phase_2/family3/kprop/eigen_norm/dataset=Books-History/feature=eigen_norm/feature_dim=3200/mechanism=mbm/x_eps=inf/m=best/norm=false/smoother=kprop/backbone=sage/use_nfr=false/recommended_command.txt
recommended_command: /home/hzw/miniconda3/envs/HZWDP/bin/python main.py --dataset
  Books-History --feature eigen_norm --mechanism mbm --x_eps inf --m best --model
  sage --hidden_dim 16 --smoother kprop --optimizer adam --device cuda --val_ratio
  0.25 --test_ratio 0.25 --data_range 0.0 1.0 --feature_dim 3200 --norm false --collect_grad_stats
  false --gradient_clip false --gradient_clip_max_norm 1.0 --sim_epoch_refresh false
  --show_progress false --log_every_epoch false --x_steps 4 --learning_rate 0.01 --weight_decay
  0 --dropout 0.75 --max_epochs 500 --patience 150 -s 12345 -r 5 -o /home/hzw/Rethinking_GNN_DP/paper_experiments/figure1/search_phase_2/family3/kprop/eigen_norm/dataset=Books-History/feature=eigen_norm/feature_dim=3200/mechanism=mbm/x_eps=inf/m=best/norm=false/smoother=kprop/backbone=sage/use_nfr=false/final
