schema_version: 1
job_id: 3b46f9670e71
best_rank: 1
best_candidate:
  candidate_id: 46
  x_steps: 4
  learning_rate: '0.01'
  weight_decay: '0.01'
  dropout: '0.25'
  tao2: none
fixed_params:
  dataset: Books-Children
  feature: eigen_norm
  sim_reference_eps: null
  feature_dim: 3200
  scale: '16384'
  random_normal_mean: null
  random_normal_std: null
  shared_value: null
  degree_bucket_num_buckets: null
  degree_bucket_range_max: null
  deepwalk_walk_length: null
  deepwalk_number_walks: null
  deepwalk_window_size: null
  deepwalk_workers: null
  deepwalk_undirected: null
  mechanism: mbm
  x_eps: inf
  m: best
  norm: false
  norm_scale: none
  smoother: hoa
  backbone: sage
  use_nfr: false
defaults:
  dataset:
    data_range:
    - 0.0
    - 1.0
    val_ratio: 0.25
    test_ratio: 0.25
  model:
    hidden_dim: 16
  trainer:
    optimizer: adam
    collect_grad_stats: false
    gradient_clip: false
    gradient_clip_max_norm: 1.0
    sim_epoch_refresh: false
    show_progress: false
    log_every_epoch: false
  stage:
    grid:
      patience: 80
      repeats: 1
      max_epochs: 300
    verify:
      patience: 150
      repeats: 5
      max_epochs: 500
verify_metrics:
  val_acc:
    mean: 51.642642974853516
    std: 0.29788955787882476
    min: 51.225345611572266
    max: 51.97980880737305
    n: 5
  test_acc:
    mean: 51.590613555908206
    std: 0.42750790324173243
    min: 51.26177215576172
    max: 52.31801986694336
    n: 5
artifacts:
  verify_summary_csv: /home/hzw/Rethinking_GNN_DP/paper_experiments/figure1/search_phase_2/family3/hoa/eigen_norm/dataset=Books-Children/feature=eigen_norm/feature_dim=3200/scale=16384/mechanism=mbm/x_eps=inf/m=best/norm=false/smoother=hoa/backbone=sage/use_nfr=false/verify_top5_summary.csv
  recommended_command_txt: /home/hzw/Rethinking_GNN_DP/paper_experiments/figure1/search_phase_2/family3/hoa/eigen_norm/dataset=Books-Children/feature=eigen_norm/feature_dim=3200/scale=16384/mechanism=mbm/x_eps=inf/m=best/norm=false/smoother=hoa/backbone=sage/use_nfr=false/recommended_command.txt
recommended_command: /home/hzw/miniconda3/envs/HZWDP/bin/python main.py --dataset
  Books-Children --feature eigen_norm --mechanism mbm --x_eps inf --m best --model
  sage --hidden_dim 16 --smoother hoa --optimizer adam --device cuda --val_ratio 0.25
  --test_ratio 0.25 --data_range 0.0 1.0 --feature_dim 3200 --scale 16384 --norm false
  --collect_grad_stats false --gradient_clip false --gradient_clip_max_norm 1.0 --sim_epoch_refresh
  false --show_progress false --log_every_epoch false --x_steps 4 --learning_rate
  0.01 --weight_decay 0.01 --dropout 0.25 --max_epochs 500 --patience 150 -s 12345
  -r 5 -o /home/hzw/Rethinking_GNN_DP/paper_experiments/figure1/search_phase_2/family3/hoa/eigen_norm/dataset=Books-Children/feature=eigen_norm/feature_dim=3200/scale=16384/mechanism=mbm/x_eps=inf/m=best/norm=false/smoother=hoa/backbone=sage/use_nfr=false/final
