schema_version: 1
job_id: 78d8091f47c4
best_rank: 1
best_candidate:
  candidate_id: 118
  x_steps: 8
  learning_rate: '0.01'
  weight_decay: '0.01'
  dropout: '0.25'
  tao2: none
fixed_params:
  dataset: lastfm
  feature: raw
  sim_reference_eps: null
  feature_dim: null
  scale: null
  random_normal_mean: null
  random_normal_std: null
  shared_value: null
  degree_bucket_num_buckets: null
  degree_bucket_range_max: null
  deepwalk_walk_length: null
  deepwalk_number_walks: null
  deepwalk_window_size: null
  deepwalk_workers: null
  deepwalk_undirected: null
  mechanism: mbm
  x_eps: '0.001'
  m: best
  norm: true
  norm_scale: '262144'
  smoother: kprop
  backbone: sage
  use_nfr: false
defaults:
  dataset:
    data_range:
    - 0.0
    - 1.0
    val_ratio: 0.25
    test_ratio: 0.25
  model:
    hidden_dim: 16
  trainer:
    optimizer: adam
    collect_grad_stats: false
    gradient_clip: false
    gradient_clip_max_norm: 1.0
    sim_epoch_refresh: false
    show_progress: false
    log_every_epoch: false
  stage:
    grid:
      patience: 80
      repeats: 1
      max_epochs: 300
    verify:
      patience: 150
      repeats: 5
      max_epochs: 500
verify_metrics:
  val_acc:
    mean: 88.77470092773437
    std: 0.29176791856637485
    min: 88.31168365478516
    max: 89.04573059082031
    n: 5
  test_acc:
    mean: 88.19875793457031
    std: 0.9406165288138465
    min: 86.84358978271484
    max: 88.93280792236328
    n: 5
artifacts:
  verify_summary_csv: /home/hzw/Rethinking_GNN_DP/paper_experiments/figure5/figure5.yaml/dataset=lastfm/feature=raw/mechanism=mbm/x_eps=0.001/m=best/norm=true/norm_scale=262144/smoother=kprop/backbone=sage/use_nfr=false/verify_top5_summary.csv
  recommended_command_txt: /home/hzw/Rethinking_GNN_DP/paper_experiments/figure5/figure5.yaml/dataset=lastfm/feature=raw/mechanism=mbm/x_eps=0.001/m=best/norm=true/norm_scale=262144/smoother=kprop/backbone=sage/use_nfr=false/recommended_command.txt
recommended_command: /home/hzw/miniconda3/envs/HZWDP/bin/python main.py --dataset
  lastfm --feature raw --mechanism mbm --x_eps 0.001 --m best --model sage --hidden_dim
  16 --smoother kprop --optimizer adam --device cuda --val_ratio 0.25 --test_ratio
  0.25 --data_range 0.0 1.0 --norm true --norm_scale 262144 --collect_grad_stats false
  --gradient_clip false --gradient_clip_max_norm 1.0 --sim_epoch_refresh false --show_progress
  false --log_every_epoch false --x_steps 8 --learning_rate 0.01 --weight_decay 0.01
  --dropout 0.25 --max_epochs 500 --patience 150 -s 12345 -r 5 -o /home/hzw/Rethinking_GNN_DP/paper_experiments/figure5/figure5.yaml/dataset=lastfm/feature=raw/mechanism=mbm/x_eps=0.001/m=best/norm=true/norm_scale=262144/smoother=kprop/backbone=sage/use_nfr=false/final
